using CheckBarcode.Application.Ports;
using CheckBarcode.Domain;

namespace CheckBarcode.Simulator;

/// <summary>Code reader simulator: results are injected by tests or generated by the simulator console.</summary>
public sealed class SimulatedCodeReader : ICodeReader
{
    private CameraSettings _settings = new(500, 1.0, 0, 100, 200, 1);
    private Timer? _live;

    public SimulatedCodeReader(string name, CameraRole role, string address)
    {
        Name = name;
        Role = role;
        Address = address;
    }

    public string Name { get; }
    public CameraRole Role { get; }
    public string Address { get; }
    public bool IsConnected { get; private set; }
    public string? MatchString { get; private set; }
    public BarcodeFormat? MatchFormat { get; private set; }
    /// <summary>When false, ConnectAsync fails (simulates a camera that is off).</summary>
    public bool Reachable { get; set; } = true;
    /// <summary>Code returned by software trigger.</summary>
    public string NextCode { get; set; } = "";

    public event EventHandler<CodeReadResult>? ResultArrived;
    public event EventHandler<bool>? ConnectionChanged;
    public event EventHandler<byte[]>? LiveImageArrived;

    public Task ConnectAsync(CancellationToken ct)
    {
        if (!Reachable) throw new IOException($"Simulated camera {Address} not reachable");
        if (!IsConnected)
        {
            IsConnected = true;
            ConnectionChanged?.Invoke(this, true);
        }
        return Task.CompletedTask;
    }

    public Task DisconnectAsync()
    {
        if (IsConnected)
        {
            IsConnected = false;
            ConnectionChanged?.Invoke(this, false);
        }
        return Task.CompletedTask;
    }

    /// <summary>Simulates a network loss.</summary>
    public void Drop() => DisconnectAsync();

    public Task ApplyMatchStringAsync(string matchString, BarcodeFormat format)
    {
        MatchString = matchString;
        MatchFormat = format;
        return Task.CompletedTask;
    }

    public Task ClearMatchStringAsync()
    {
        MatchString = null;
        return Task.CompletedTask;
    }

    public Task StartLiveAsync()
    {
        _live ??= new Timer(_ => LiveImageArrived?.Invoke(this, TinyPng.Create(Role == CameraRole.Box ? (byte)200 : (byte)120)), null, 0, 500);
        return Task.CompletedTask;
    }

    public Task StopLiveAsync()
    {
        _live?.Dispose();
        _live = null;
        return Task.CompletedTask;
    }

    public Task TriggerAsync()
    {
        Emit(NextCode);
        return Task.CompletedTask;
    }

    /// <summary>Raises a read result as if the camera had been triggered by the machine.</summary>
    public void Emit(string code, DateTime? utc = null)
    {
        if (!IsConnected) return;
        ResultArrived?.Invoke(this, new CodeReadResult(code, TinyPng.Create(string.IsNullOrEmpty(code) ? (byte)40 : (byte)220), utc ?? DateTime.UtcNow));
    }

    private Timer? _auto;
    private readonly Random _random = new();

    /// <summary>Demo mode: emits a result every <paramref name="intervalMs"/> while connected and a match string is set.</summary>
    public void StartAuto(int intervalMs = 1200, double failRate = 0.03, double noReadRate = 0.02)
    {
        _auto?.Dispose();
        _auto = new Timer(_ =>
        {
            if (!IsConnected || string.IsNullOrEmpty(MatchString)) return;
            var r = _random.NextDouble();
            var code = r < noReadRate ? "" : r < noReadRate + failRate ? MatchString + "9" : MatchString;
            Emit(code);
        }, null, intervalMs, intervalMs);
    }

    public Task<CameraSettings> GetSettingsAsync() => Task.FromResult(_settings);

    public Task SetSettingsAsync(CameraSettings settings)
    {
        _settings = settings;
        return Task.CompletedTask;
    }

    public Task<string> GetSerialAsync() => Task.FromResult("SIM-" + Address);

    public void Dispose()
    {
        _live?.Dispose();
        _auto?.Dispose();
    }
}

/// <summary>Builds a small valid grayscale PNG (no System.Drawing needed).</summary>
public static class TinyPng
{
    public static byte[] Create(byte gray, int width = 64, int height = 36)
    {
        using var ms = new MemoryStream();
        ms.Write(new byte[] { 0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A });
        var ihdr = new byte[13];
        System.Buffers.Binary.BinaryPrimitives.WriteInt32BigEndian(ihdr, width);
        System.Buffers.Binary.BinaryPrimitives.WriteInt32BigEndian(ihdr.AsSpan(4), height);
        ihdr[8] = 8; // bit depth
        ihdr[9] = 0; // grayscale
        Chunk(ms, "IHDR", ihdr);
        var raw = new byte[(width + 1) * height];
        for (var y = 0; y < height; y++)
            for (var x = 0; x < width; x++)
                raw[y * (width + 1) + 1 + x] = (byte)((x / 8 + y / 6) % 2 == 0 ? gray : gray / 2);
        using var z = new MemoryStream();
        using (var zs = new System.IO.Compression.ZLibStream(z, System.IO.Compression.CompressionLevel.Fastest, true)) zs.Write(raw);
        Chunk(ms, "IDAT", z.ToArray());
        Chunk(ms, "IEND", Array.Empty<byte>());
        return ms.ToArray();
    }

    private static void Chunk(Stream s, string type, byte[] data)
    {
        Span<byte> len = stackalloc byte[4];
        System.Buffers.Binary.BinaryPrimitives.WriteInt32BigEndian(len, data.Length);
        s.Write(len);
        var typeBytes = System.Text.Encoding.ASCII.GetBytes(type);
        s.Write(typeBytes);
        s.Write(data);
        var crc = Crc32(typeBytes.Concat(data).ToArray());
        Span<byte> c = stackalloc byte[4];
        System.Buffers.Binary.BinaryPrimitives.WriteUInt32BigEndian(c, crc);
        s.Write(c);
    }

    private static uint Crc32(byte[] data)
    {
        uint crc = 0xFFFFFFFF;
        foreach (var b in data)
        {
            crc ^= b;
            for (var k = 0; k < 8; k++) crc = (crc & 1) != 0 ? (crc >> 1) ^ 0xEDB88320 : crc >> 1;
        }
        return ~crc;
    }
}
