namespace CheckBarcode.Application.Reports;

public enum ColumnAlign
{
    Left,
    Center,
    Right,
}

public sealed record ReportColumn(string Header, double Weight = 1, ColumnAlign Align = ColumnAlign.Left);

public sealed class ReportTable
{
    public List<ReportColumn> Columns { get; } = new();
    public List<string[]> Rows { get; } = new();

    public ReportTable Col(string header, double weight = 1, ColumnAlign align = ColumnAlign.Left)
    {
        Columns.Add(new ReportColumn(header, weight, align));
        return this;
    }

    public void Row(params string[] cells) => Rows.Add(cells);
}

/// <summary>One block of a report: optional heading, key/value fields, paragraph and/or table.</summary>
public sealed class ReportSection
{
    public string? Heading { get; set; }
    public List<KeyValuePair<string, string>> Fields { get; } = new();
    public string? Text { get; set; }
    public ReportTable? Table { get; set; }
}

/// <summary>Renderer-independent report model (PDF writer and WPF print preview render the same model).</summary>
public sealed class ReportDocument
{
    public string Title { get; set; } = "";
    public string Subtitle { get; set; } = "";
    public bool Landscape { get; set; } = true;
    /// <summary>Lines printed under the title on the first page (machine, customer, period…).</summary>
    public List<KeyValuePair<string, string>> Header { get; } = new();
    public List<ReportSection> Sections { get; } = new();
    /// <summary>Printed at the bottom of every page (integrity result, generated by/at).</summary>
    public string Footer { get; set; } = "";
    /// <summary>Text used for "Page {0} of {1}".</summary>
    public string PageFormat { get; set; } = "Page {0}/{1}";
    /// <summary>Short machine-readable kind, used in file names: BATCH, AUDIT, ALARM, LOG, BATCHLIST.</summary>
    public string Kind { get; set; } = "";
    public long? BatchId { get; set; }
    public string FileTag { get; set; } = "";

    public ReportSection AddSection(string? heading = null)
    {
        var s = new ReportSection { Heading = heading };
        Sections.Add(s);
        return s;
    }
}
